stages:
  - test
  - publish

pytest:
  image: docker.sertit.unistra.fr/sertit/eo-containers/python:3.7
  stage: test
  before_script:
    - pip install coverage pytest pytest-cov
    - python setup.py develop
  script:
    - pytest -v --cov-report term --cov=sertit_utils CI/SCRIPTS
    - coverage xml
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  artifacts:
    when: always
    paths:
      - coverage
  tags:
    - linux

upload_wheel:linux:
  image: python:3.7-buster
  stage: publish
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${DEPLOY_PWD} TWINE_USERNAME=${DEPLOY_NAME} python -m twine upload --verbose --repository-url https://code.sertit.unistra.fr/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  tags:
    - linux
  only:
    - tags