stages:
  - test
  - publish

pytest:
  image: docker.sertit.unistra.fr/sertit/eo-containers/python:3.7
  stage: test
  script:
    - pytest CI/SCRIPTS -v
  tags:
    - linux

upload_wheel:linux:
  image: python:3.7-buster
  stage: publish
  script:
    - pip install twine
    - TWINE_PASSWORD=${DEPLOY_PWD} TWINE_USERNAME=${DEPLOY_NAME} python -m twine upload --verbose --repository-url https://code.sertit.unistra.fr/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*