stages:
  - build
  - test
  - publish
  - docs

lint:
  image: python:3.7-buster
  stage: build
  script:
    - python -m pip install --upgrade pip
    - pip install flake8
    - flake8 .
  tags:
    - linux
  except:
    changes:
      - "*.md"
      - sertit/version.py
      - doc_template/*

pytest:
  image: docker.sertit.unistra.fr/extracteo/extracteo_deps:latest
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -e .[full]
  script:
    - pytest -v --durations=0 --cov-report term --cov-report xml:cov.xml --cov=sertit CI/SCRIPTS
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  tags:
    - linux
  except:
    changes:
      - "*.md"
      - sertit/version.py
      - doc_template/*

upload_wheel:linux:
  image: python:3.7-buster
  stage: publish
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${PYPI_PWD} TWINE_USERNAME=${PYPI_TOKEN} python -m twine upload dist/*
  tags:
    - linux
  only:
    - tags

pages:
  image: docker.sertit.unistra.fr/sertit/eo-containers/python:3.7
  stage: docs
  script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - pdoc sertit -o docs -f --html --template-dir doc_template
    - mv docs/ public/
  artifacts:
    paths:
      - public
  tags:
    - linux
  only:
    - master
