stages:
  - lint
  - test
  - publish
  - weekly_tests

variables:
  EEO_DEPS: $REGISTRY_GITLAB/extracteo/extracteo_deps
  EO_CONTAINER: $REGISTRY_GITLAB/eo-containers/python

lint:
  image: python:3.7-buster
  stage: lint
  script:
    - python -m pip install --upgrade pip
    - pip install flake8
    - flake8 .
  except:
    - tags

pytest:
  image: $EEO_DEPS:latest
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install --ignore-installed PyYAML
    - pip install -e .[full]
  script:
    - pytest -v --durations=0 --cov-report term --cov-report xml:cov.xml --cov=sertit CI/SCRIPTS --cov-config=.coveragerc
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  tags:
    - sertit
    - linux
  rules:
    - if: '$CI_COMMIT_TAG == null'
    - changes:
        - sertit/**/*.{py,xml}
        - CI/**/*.{py,xml}
        - .gitlab-ci.yml
        - pytest.ini
  needs: [ "lint" ]

tox-linux-3.7:on-schedule:
  image: $EO_CONTAINER:3.7
  stage: weekly_tests
  before_script:
    - python -m pip install --upgrade pip
    - pip install tox
  script:
    - tox -c tox.ini -e py37
  tags:
    - sertit
    - linux
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

tox-linux-3.8:on-schedule:
  image: $EO_CONTAINER:3.8
  stage: weekly_tests
  before_script:
    - python -m pip install --upgrade pip
    - pip install tox
  script:
    - tox -c tox.ini -e py38
  tags:
    - sertit
    - linux
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

tox-linux-3.9:on-schedule:
  image: $EO_CONTAINER:3.9
  stage: weekly_tests
  before_script:
    - python -m pip install --upgrade pip
    - pip install tox
  script:
    - tox -c tox.ini -e py39
  tags:
    - sertit
    - linux
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

tox-windows:on-schedule:
  stage: weekly_tests
  before_script:
    - pip install tox
  script:
    - tox -c tox-conda.ini
  tags:
    - sertit
    - windows
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
