stages:
  - test
  - publish
  - doc

pytest:
  image: docker.sertit.unistra.fr/sertit/eo-containers/python:3.7
  stage: test
  before_script:
    - pip install coverage pytest pytest-cov
    - python setup.py develop
  script:
    - pytest -v --cov-report term --cov-report xml:cov.xml --cov=sertit_utils CI/SCRIPTS
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  tags:
    - linux

upload_wheel:linux:
  image: python:3.7-buster
  stage: publish
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${DEPLOY_PWD} TWINE_USERNAME=${DEPLOY_NAME} python -m twine upload --verbose --repository-url https://code.sertit.unistra.fr/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  tags:
    - linux
  only:
    - tags

pages:
  image: python:3.7-buster
  stage: doc
  script:
    - pip install pdoc3
    - pdoc sertit_utils -o docs/html -f --html
  artifacts:
    paths:
      - docs/html
  tags:
    - linux
  only:
    - master
