name: sertit
channels:
  - conda-forge
dependencies:         # everything under this, installed by conda
  - python==3.7.11
  - pip
  - pip:                # everything under this, installed by pip
      - --extra-index-url ${WINDOWS_WHEELS}  # Use windows wheels on windows
      - -r requirements.txt
