name: Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 7 * * 1"
  workflow_dispatch:

jobs:
  lint:
    name: Linters (pre-commit)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Run pre-commit action
      uses: pre-commit/action@v2.0.0

  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest]  # , windows-latest]  # rasterio and geopandas cant be installed easily on Windows
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install GDAL
      run: |
        sudo apt-get update && \
          sudo apt-get upgrade -y && \
          sudo apt-get install -y python-numpy gdal-bin libgdal-dev && \
          export CPLUS_INCLUDE_PATH="/usr/include/gdal" && \
          export C_INCLUDE_PATH="/usr/include/gdal"
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - name: Get current week number
      id: get-week
      shell: bash
      run: echo "::set-output name=week::$(date +'%V')"
    - name: Pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ steps.get-week.outputs.week }}-${{ hashFiles('setup.py') }}
    - name: Install tox and tox-gh-actions
      run: python -m pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
